version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.1

jobs:
  build:
    docker:
      - image: node:12-buster
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run postinstall
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - tests
            - node_modules
            - package.json
            - app
  test-qbittorrent:
    docker:
      - image: circleci/node:12-browsers
      - image: linuxserver/qbittorrent
    steps:
      - attach_workspace:
          at: ./
      - run: npm test -- -g qbittorrent
  test-transmission:
    docker:
      - image: circleci/node:12-browsers
      - image: linuxserver/transmission
        environment:
          USER: username
          PASS: password
    steps:
      - attach_workspace:
          at: ./
      - run: npm test -- -g transmission
  test-rtorrent:
    docker:
      - image: circleci/node:12-browsers
      - image: linuxserver/rutorrent
        environment:
          USER: username
          PASS: password
    steps:
      - attach_workspace:
          at: ./
      - run: npm test -- -g rtorrent

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-qbittorrent:
          requires:
            - build
      - test-transmission:
          requires:
            - build
